apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: go-simple-webserver
  labels:
    app: go-simple-webserver
spec:
  replicas: 10
  strategy:
    canary:
      steps:
        - setWeight: 50
        - pause: { duration: 60s }
        - setWeight: 100
  selector:
    matchLabels:
      app: go-simple-webserver
  template:
    metadata:
      labels:
        app: go-simple-webserver
    spec:
      containers:
        - name: webserver
          image: ghcr.io/2amazing4me/go-simple-webserver@sha256:3c5b0a9909a0c2558c527db2fb9d07782feb8b107a47f6cbf5464d1780d63b97
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
